// 领域规则被违反时抛出；code 供调用方做程序化分支，meta 携带可售数、缺口等事实。
export class DomainError extends Error {
  constructor(code, message, meta = {}) {
    super(message);
    this.name = "DomainError";
    this.code = code;
    this.meta = meta;
  }
}

export const Codes = {
  UNKNOWN_EVENT: "UNKNOWN_EVENT",
  CONCURRENT_WRITE: "CONCURRENT_WRITE",
  CAPACITY_EXCEEDED: "CAPACITY_EXCEEDED",
  INSUFFICIENT_COMPONENTS: "INSUFFICIENT_COMPONENTS",
  INSUFFICIENT_SELLABLE: "INSUFFICIENT_SELLABLE",
  RELEASE_BLOCKED: "RELEASE_BLOCKED",
  RESERVATION_NOT_HELD: "RESERVATION_NOT_HELD",
  RESERVATION_EXPIRED: "RESERVATION_EXPIRED",
  ORDER_NOT_OPEN: "ORDER_NOT_OPEN",
  DESIGN_VERSION_NOT_CLEARED: "DESIGN_VERSION_NOT_CLEARED",
  LICENSE_OUT_OF_SCOPE: "LICENSE_OUT_OF_SCOPE",
  LABEL_NOT_CURRENT: "LABEL_NOT_CURRENT",
  LOT_NOT_USABLE: "LOT_NOT_USABLE",
  BATCH_NOT_USABLE: "BATCH_NOT_USABLE",
  LOT_EXPIRED: "LOT_EXPIRED",
  SELECTIONS_NOT_CONFIRMED: "SELECTIONS_NOT_CONFIRMED",
  UNKNOWN_FLAVOR: "UNKNOWN_FLAVOR",
  NOTHING_TO_SETTLE: "NOTHING_TO_SETTLE",
  SETTLEMENT_MISMATCH: "SETTLEMENT_MISMATCH"
};

export function fail(code, message, meta) {
  throw new DomainError(code, message, meta);
}
